## Data

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("/content/train.csv")
df

,ID,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,y
0,0,58238,971.303,397.202654,186.945510,2.124697,0.882317,58977,272.306674,0.604756,0.987470,0.775723,0.685561,0.006820,0.000929,0.469994,0.998595,HOROZ
1,1,44515,757.601,265.590470,213.967453,1.241266,0.592420,44780,238.071960,0.771745,0.994082,0.974620,0.896387,0.005966,0.002376,0.803510,0.997370,SEKER
2,2,31662,653.783,239.902428,168.421505,1.424417,0.712136,32034,200.781748,0.801407,0.988387,0.930853,0.836931,0.007577,0.002293,0.700453,0.997737,DERMASON
3,3,38778,734.020,268.446281,184.061923,1.458456,0.727925,39208,222.201897,0.766137,0.989033,0.904439,0.827733,0.006923,0.002005,0.685142,0.999250,DERMASON
4,4,42530,775.403,281.212824,193.236878,1.455275,0.726511,43028,232.703412,0.729816,0.988426,0.888895,0.827499,0.006612,0.001912,0.684755,0.996507,SIRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10829,10829,37777,716.007,250.174662,192.704033,1.298233,0.637708,38174,219.315230,0.770519,0.989600,0.925983,0.876648,0.006622,0.002413,0.768513,0.997708,SEKER
10830,10830,32187,667.621,247.778775,165.786862,1.494562,0.743179,32582,202.439525,0.731805,0.987877,0.907466,0.817017,0.007698,0.002116,0.667517,0.997646,DERMASON
10831,10831,81837,1095.937,433.838186,241.527026,1.796230,0.830699,82554,322.797312,0.771996,0.991315,0.856226,0.744050,0.005301,0.001002,0.553610,0.994412,CALI
10832,10832,48212,826.362,309.639462,199.285811,1.553746,0.765357,48777,247.760822,0.677002,0.988417,0.887206,0.800159,0.006422,0.001624,0.640255,0.994793,SIRA
10833,10833,28026,610.943,215.446569,165.740377,1.299904,0.638903,28302,188.901592,0.776688,0.990248,0.943560,0.876791,0.007687,0.002802,0.768762,0.999317,DERMASON

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10834 entries, 0 to 10833
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               10834 non-null  int64
 1   Area             10834 non-null  int64
 2   Perimeter        10834 non-null  float64
 3   MajorAxisLength  10834 non-null  float64
 4   MinorAxisLength  10834 non-null  float64
 5   AspectRation     10834 non-null  float64
 6   Eccentricity     10834 non-null  float64
 7   ConvexArea       10834 non-null  int64
 8   EquivDiameter    10834 non-null  float64
 9   Extent           10834 non-null  float64
 10  Solidity         10834 non-null  float64
 11  roundness        10834 non-null  float64
 12  Compactness      10834 non-null  float64
 13  ShapeFactor1     10834 non-null  float64
 14  ShapeFactor2     10834 non-null  float64
 15  ShapeFactor3     10834 non-null  float64
 16  ShapeFactor4     10834 non-null  float64
 17  y                10834 non-null  object
dtypes: float64(14), int64(3), object(1)
memory usage: 1.5+ MB

In [5]:
df.isnull().sum()

ID                 0
Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
y                  0
dtype: int64

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,10834.0,5416.500000,3127.650742,0.000000,2708.250000,5416.500000,8124.750000,10833.000000
Area,10834.0,53095.675189,29542.542580,20420.000000,36343.500000,44645.000000,61295.000000,254616.000000
Perimeter,10834.0,855.274892,214.991122,524.932000,703.601250,793.739500,975.517500,1985.370000
MajorAxisLength,10834.0,320.036169,85.961630,183.601165,253.501071,296.377365,376.068399,738.860153
MinorAxisLength,10834.0,202.410342,45.113965,129.576207,175.927024,192.525040,217.315195,450.926187
AspectRation,10834.0,1.581294,0.244314,1.024868,1.432985,1.550761,1.703029,2.388873
Eccentricity,10834.0,0.750588,0.091481,0.218951,0.716250,0.764314,0.809450,0.908167
ConvexArea,10834.0,53816.205926,29999.710739,20684.000000,36731.250000,45148.000000,62251.500000,263261.000000
EquivDiameter,10834.0,253.123583,59.433080,161.243764,215.113880,238.419335,279.362162,569.374358
Extent,10834.0,0.749937,0.048949,0.555315,0.718778,0.760141,0.786871,0.866195
Solidity,10834.0,0.987152,0.004626,0.919246,0.985627,0.988290,0.990014,0.994677
roundness,10834.0,0.873647,0.059344,0.489618,0.833479,0.883472,0.916883,0.990685
Compactness,10834.0,0.800244,0.061228,0.645368,0.763378,0.801428,0.834068,0.987303
ShapeFactor1,10834.0,0.006559,0.001127,0.002856,0.005888,0.006643,0.007268,0.009897
ShapeFactor2,10834.0,0.001718,0.000593,0.000564,0.001161,0.001700,0.002169,0.003665
ShapeFactor3,10834.0,0.644139,0.098268,0.416499,0.582747,0.642287,0.695670,0.974767
ShapeFactor4,10834.0,0.995083,0.004306,0.947687,0.993690,0.996397,0.997895,0.999733

In [7]:
df.duplicated().sum()

0

## Spliting data

In [8]:
from sklearn.model_selection import cross_val_score,train_test_split

df_train, df_val = train_test_split(df, test_size=0.2, random_state=42)

X_train = df_train.drop(columns=['ID', 'y' ,'ShapeFactor3','Compactness','AspectRation','Area','MajorAxisLength','MinorAxisLength','ConvexArea','EquivDiameter','ShapeFactor1' ])
y_train = df_train['y']

X_val = df_val.drop(columns=['ID', 'y' , 'ShapeFactor3','Compactness','AspectRation','Area','MajorAxisLength','MinorAxisLength','ConvexArea','EquivDiameter','ShapeFactor1' ])
y_val = df_val['y']


print(X_train.shape,X_val.shape,y_train.shape,y_val.shape)

(8667, 7) (2167, 7) (8667,) (2167,)

## Training Model

In [9]:
# #train decision tree model 
# from sklearn.tree import DecisionTreeClassifier

# # Create an instance of the classifier
# classifier = DecisionTreeClassifier(random_state=42)

# # Train the classifier
# classifier = classifier.fit(X_train, y_train)
# y_pred = classifier.predict(X_val)

In [10]:
# # Train logistic regression model
# from sklearn.linear_model import LogisticRegression
# lr_model = LogisticRegression(random_state=42)
# lr_model.fit(X_train, y_train)
# y_pred = lr_model.predict(X_val)

In [11]:
# # Train SVM model 
# from sklearn.svm import SVC
# svm_model = SVC(random_state=42)
# svm_model.fit(X_train, y_train)
# y_pred = svm_model.predict(X_val)

In [12]:
# # Train KNeighborsClassifier model
# from sklearn.neighbors import KNeighborsClassifier
# neigh = KNeighborsClassifier()
# neigh.fit(X_train, y_train)
# y_pred = neigh.predict(X_val)

In [13]:
# Train random forest model 
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_val)

In [14]:
# #Train KNeighborsClassifier Model 
# from sklearn.neighbors import KNeighborsClassifier
# k = 7
# neigh = KNeighborsClassifier(n_neighbors = k).fit(X_train,y_train)
# y_pred = neigh.predict(X_val)

In [15]:
# # train XGBoost Model
# from xgboost import XGBClassifier
# model = XGBClassifier()
# model.fit(X_train, y_train)
# y_pred2 = model.predict(X_val)

## Accuarcy of Training

In [16]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_train,rf_model.predict(X_train))
print ( 'Accuracy = ', accuracy)

Accuracy =  1.0

## Accuarcy Val

In [17]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_val,y_pred)
print ( 'Accuracy = ', accuracy)

Accuracy =  0.9312413474850023

In [18]:
compare = pd.DataFrame({'preds':y_pred , 'y':y_val})
compare.head(5)

         preds         y
1766  DERMASON  DERMASON
6590      CALI      CALI
4184  DERMASON  DERMASON
2109      SIRA      SIRA
3181  BARBUNYA  BARBUNYA

##Test Data##

In [19]:
test=pd.read_csv("/content/test.csv")
x_test=test.drop(columns=['ID','ShapeFactor3','Compactness','AspectRation','Area','MajorAxisLength','MinorAxisLength','ConvexArea','EquivDiameter','ShapeFactor1' ])

In [20]:
x_test.dtypes.value_counts()

float64    7
dtype: int64

In [21]:
preds_test = rf_model.predict(x_test)

## submission

In [22]:
# Save test predictions to file
output = pd.DataFrame({'Id': x_test.index,
                       'y': preds_test})
output.to_csv('submission.csv', index=False)

In [23]:
output.head()

   Id         y
0   0     HOROZ
1   1  DERMASON
2   2  BARBUNYA
3   3  DERMASON
4   4    BOMBAY